apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecg-sql-proxy
  namespace: ecg-prod  # Make sure this matches your overlay namespace
  annotations:
    # Replace [YOUR_GSA_EMAIL] with your actual Google Service Account email
    iam.gke.io/gcp-service-account: ecg-sql-proxy@ecg-mlops-project.iam.gserviceaccount.com