apiVersion: v1
kind: Service
metadata:
  name: ecg-api
  labels:
    app: ecg-api
    project: ecg-recommender
spec:
  selector:
    app: ecg-api
    project: ecg-recommender
  ports:
  - name: http          # Add this line!
    port: 80
    targetPort: 8000
  type: ClusterIP